### ISSUE TITLE
Contract audit and FAQ

### ISSUE THREAD

**Issue by victorbinetruypic** [Smart-Chain-git/SMAK-Staking#12]
On both the staking and lottery page, "👉 This smart contract has been audited" will now be inside a button (see design below). Next to it will also be "FAQ" inside a button (FAQ will bring the user to the same page as the FAQ inside the menu

MOBILE VIEW:
<img width="277" alt="Screenshot 2021-08-18 at 11 45 02" src="https://user-images.githubusercontent.com/87120226/129876804-522fa0e3-3237-4bd8-8cde-481e6d3b1a8c.png">

DESKTOP VIEW:

<img width="553" alt="Screenshot 2021-08-18 at 11 45 14" src="https://user-images.githubusercontent.com/87120226/129876825-a92dbc48-a587-47eb-95b7-a44348ab5937.png">

**Comment by Smartlinkso** [comment]
5- Mettre un hover plus doux (ajouter une transition css) sur les liens des pages. 

<img width="372" alt="Screen Shot 2021-09-06 at 12 53 34 PM" src="https://user-images.githubusercontent.com/78213740/132257203-5d11e5bf-3298-499c-af9e-6798c7aa762c.png">
