### ISSUE TITLE
Version 1.5

### ISSUE THREAD

**Issue by victorbinetruypic** [Smart-Chain-git/SMAK-Staking#15]
At the bottom of the Staking page, change the versioning info to V1.5

At the bottom of the lottery page, change the versioning info to V1.5

**Comment by BalbuBlock** [comment]
At the bottom of the Staking page (292,542,598), change Circulating (292,542,598) to 305 492 627

**Comment by victorbinetruypic** [comment]
Circulating supply has been changed but the versioning hasn't been updated yet

**Comment by BalbuBlock** [comment]
I propose V 1.5 when all the refacto + all the tickets are good

**Comment by victorbinetruypic** [comment]
Alright 'ill update the ticket.
