### ISSUE TITLE
Wording update for V.1.1

### ISSUE THREAD

**Issue by victorbinetruypic** [Smart-Chain-git/SMAK-Staking#2]
On the "SMAK Staking Contract Details" card at the bottom right of the dashboard screen:

1. Replace V1.01 by V1.1
2. Place "Circulating" info under "Number of Stakers"
3. Place "Market Cap" info under "Circulating" 
4. Rename "Fully Diluted Market Cap" by "Max Supply Cap" and Place this info under "Market Cap" info
5. Under Max Supply Cap, place "SMAK Burn" Info
﻿﻿

**Comment by anastasiaDuchesne** [comment]
![image](https://user-images.githubusercontent.com/58977489/125946174-59740169-cfad-4561-88da-6406447903ac.png)
Is this alright? @victorbinetruypic

**Comment by victorbinetruypic** [comment]
Oui c'est parfait merci.
