### ISSUE TITLE
Changement Front Staking

### ISSUE THREAD

**Issue by victorbinetruypic** [Smart-Chain-git/SMAK-Staking#5]
1. Ajouter le bouton "white mode" a la version mobile 
<img width="843" alt="Screenshot 2021-08-18 at 11 08 24" src="https://user-images.githubusercontent.com/87120226/129871158-46ce8acd-b05a-4640-bb39-30e4c00ba245.png">

2. Sur la pop-up unstaking (quand tu unstake une position) le bouton MAX n’est pas au milieu de l’input
<img width="447" alt="Screenshot 2021-08-18 at 11 09 39" src="https://user-images.githubusercontent.com/87120226/129871309-b1ba74c4-dcea-4d75-a755-e37b13794d5a.png">

3. Dans My Staking Details, centrer les details d'une position avec le titre du tableau 
<img width="1016" alt="Screenshot 2021-08-18 at 11 11 30" src="https://user-images.githubusercontent.com/87120226/129871609-f7e671ba-1296-474c-8350-06376c7ad1a3.png">

**Comment by victorbinetruypic** [comment]
This issue has been implemented but points 2 & 3 haven't been tested by a user because on the current deployment we couldn't create a transaction.

**Comment by Smartlinkso** [comment]
4. Live Mainnet apparait 2 fois. Ne garder que celui au dessus des reseaux sociaux

<img width="288" alt="Screen Shot 2021-09-06 at 10 43 42 AM" src="https://user-images.githubusercontent.com/78213740/132249972-659a9025-65ad-411e-90a1-89254bdcfcff.png">

**Comment by Smartlinkso** [comment]
6- Attention, le font Source Sans Pro n'est pas respecté sur la lotterie et quelques endroits du staking 

<img width="324" alt="Screen Shot 2021-09-06 at 12 54 59 PM" src="https://user-images.githubusercontent.com/78213740/132257294-cbfcf83f-3b1b-4254-9e99-49f51d3704c6.png">

**Comment by victorbinetruypic** [comment]
The last two comments have been added to separate issues
